### ISSUE TITLE
Rename to decidim-module-department_admin

### ISSUE THREAD

**Issue by andreslucena** [gencat/decidim-module-department_admin#22]
Please read regarding using underscore on [gems CamelCase](https://guides.rubygems.org/name-your-gem/) names and also using the prefix [decidim-module on GitHub repository](https://github.com/decidim/decidim/blob/e181d7e67bdf915a3a8e58416c683f52346de047/docs/advanced/how_to_create_a_module.md) name.

**Comment by tramuntanal** [comment]
Hi @andreslucena sorry for being so late,
The gem name has always followed the gem name convention, but it is true that the URL of the repo does not. We'll tackle this issue during this October.

Can you confirm that `decidim-module-*` is still a convention? we'll be pleased to rename the module if it is like that, but I ask because I see lots of modules not following this naming convention.

**Comment by andreslucena** [comment]
> Can you confirm that decidim-module-* is still a convention? 

Yes, it is. It's in the [official module doc page](https://docs.decidim.org/en/develop/modules/)

> If you upload it to GitHub, do it with the naming decidim-module-<engine_name>, so it’s easier to find on the dependency graph. See discussion at GitHub.

> we'll be pleased to rename the module if it is like that, but I ask because I see lots of modules not following this naming convention.

Please send me the links so I can be pinging them also. Thanks!!

**Comment by tramuntanal** [comment]
Thanks for your feedback. This repository url has been renamed.

I got confused because I was thinking that this naming convention was about the gem name, but in reality it is about the repositroy URL. That's why I saw so many modules without the convention in the gem name but now I see that all was about the repository's URL.

By the way, we've also renamed https://github.com/gencat/decidim-module-challenges and https://github.com/gencat/decidim-module-idcat_mobil

**Comment by andreslucena** [comment]
> Thanks for your feedback. This repository url has been renamed.

Great!! 

> I got confused because I was thinking that this naming convention was about the gem name, but in reality it is about the repositroy URL. That's why I saw so many modules without the convention in the gem name but now I see that all was about the repository's URL.

I think that's because in the [first document](https://github.com/decidim/decidim/blob/e181d7e67bdf915a3a8e58416c683f52346de047/docs/advanced/how_to_create_a_module.md) that I sent you it wasn't that clear, but in the [next version](https://docs.decidim.org/en/develop/modules/) is it better, or at least a little clearer. If you have any ideas in how to improve this doc, let me know!

**Comment by tramuntanal** [comment]
I find that the new version is clear enough.
